exclude_patterns:
  - "tests/"
  - "spec/"
  - "**/vendor/"
  - "**/node_modules/"
  - "package-lock.json"
  - "package.json"
  - "*.md"
  - "**/*.spec.js"
  - "**/*.test.js"
  - "**/routes/"
  - "**/database/"
similar-code:
  enabled: false
method-complexity:
  enabled: false